### ISSUE TITLE
Assignment (12/4-17)

### ISSUE THREAD

**Issue by Froggzoria** [Froggzoria/PA1415_FO_MT_SD#4]
**Work delegation:**

* User Stories - Group, Max upload
* Use Case Overview - Max
* Implementation Plan + Dictionary to Max - Fredrik
* Detailed Use Cases for First Iteration + Link user stories for Max - Sam

**Comment by malformedpeach** [comment]
[Detailed Use Cases for first iteration.docx](https://github.com/Froggzoria/PA1415_FO_MT_SD/files/913994/Detailed.Use.Cases.for.first.iteration.docx)

**Comment by Froggzoria** [comment]
[Actors_Dictionary.txt](https://github.com/Froggzoria/PA1415_FO_MT_SD/files/914052/Actors_Dictionary.txt)

**Comment by malformedpeach** [comment]
[Detailed Use Cases for first iteration.docx](https://github.com/Froggzoria/PA1415_FO_MT_SD/files/914201/Detailed.Use.Cases.for.first.iteration.docx)

**Comment by malformedpeach** [comment]
[Detailed Use Cases for first iteration (updated).docx](https://github.com/Froggzoria/PA1415_FO_MT_SD/files/914328/Detailed.Use.Cases.for.first.iteration.updated.docx)

**Comment by malformedpeach** [comment]
[Use Case  Overview 3, 4.docx](https://github.com/Froggzoria/PA1415_FO_MT_SD/files/914433/Use.Case.Overview.3.4.docx)

**Comment by malformedpeach** [comment]
[Detailed Use Cases for first iteration (ALL USE CASES).docx](https://github.com/Froggzoria/PA1415_FO_MT_SD/files/914689/Detailed.Use.Cases.for.first.iteration.ALL.USE.CASES.docx)

**Comment by malformedpeach** [comment]
[Detailed Use Cases for First Iteration (ALL USE CASES).docx](https://github.com/Froggzoria/PA1415_FO_MT_SD/files/914720/Detailed.Use.Cases.for.First.Iteration.ALL.USE.CASES.docx)

**Comment by malformedpeach** [comment]
[Detailed Use Cases for First Iteration (ALL USE CASES).docx](https://github.com/Froggzoria/PA1415_FO_MT_SD/files/914729/Detailed.Use.Cases.for.First.Iteration.ALL.USE.CASES.docx)
